language: c

compiler:
  - clang
  - gcc

env:
  global:
   - secure: "Bumko1MHEwJ4nKe4WLxoBvM8muJXP76x/+1hoTwMR8K87urcTooI9BaHARN+VNCVi/fRqhs1gPKwt/YO5NkgUtf61g5jIT8dwR1MC4FIOA6EyGN3TyGH4Gi8uTfFm0g2Q0oihi3h5YR0XC+bRcgrac3CqYqT0jhp1iy5RQTNswqCgkELoQtT/cjRD8vfElu32RzMRfEWPN65HkurgahVdXG58e9HFvDbzMxJhWY+vNNbc7ZndRK/GnsF9fzHC1ZcF8hE/5i6P4M9Dd6/p1S+dVYR0VYfT8eHUpCfQ36Uv4fiFgC6dpSNSLdFs0eksYWx6rbixvIL+/N/CeoT7clWcTQupZrUaz4ucagMYOjUD2XBwZE9iebmsFOScbPqgwUsYCubKDbREyvkZG+OTXPReiGOA3QGTPauGmiGklhn+B/Xo1h9/0E8DwOjOq3ODB3V5i20PRjOQt62LQYuY1OR8K8dxWdMjdu/SBPWWnutVOzrs4dpPAWcYYZldZ+j1U2huBLAPuXKnwFBxAP/GQj8QYoMyytPm83r9DgJe2llc3NTs7/jnxQq1BjJF5MsBRq4nQBNTRMUEMdgO39xjpR1ccP2wjlRroloH/D0bPMW58rN+hzRDQwDc7upSa9tNC1hT5FaIfmUi463FiZFxooKgADBVyqJJD1D8v0X0+mLKFw="

addons:
  coverity_scan:
    project:
      name: "geoffleyland/assignment"
      description: "Hungarian algorithm for the assignment problem"
    notification_email: geoff.leyland@incremental.co.nz
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: master

install: make test-data

script: make test
